### ISSUE TITLE
Enable/Disable preview panes

### ISSUE THREAD

**Issue by mjthoraval** [windingwind/zotero-pdf-preview#29]
I am a bit confused on what the option "Enable Preview" should be doing in the Zotero Preferences.
![image](https://user-images.githubusercontent.com/36054098/195769580-fbcae2c7-13e1-4247-ba0f-51a5d698ab4e.png)
If I disable this option, the Preview in Info Tab stays there, but keeps the last loaded preview, and does not change anymore when switching items.
If I disable "Enable Preview" and "Preview in Preview Tab", a ghost Preview Tab still remains.

A Zotero restart clears the preview, but both ghost preview panes remain:
![image](https://user-images.githubusercontent.com/36054098/195770091-1ca71b8c-696c-470d-be46-f6579a6c6e6c.png)

Should the option "Enable Preview" be a master control of "Preview in Info Tab" & "Preview in Preview Tab"? In that case these two secondary options should be disabled when switching off "Enable Preview".
Or is there another use case for this option?

**Comment by windingwind** [comment]
Fixed in v0.3.3. Currently it requires restarting Zotero to apply.

This option will be removed in the future, as in Zotero 7 all plugins can be disabled without restarting.

**Comment by mjthoraval** [comment]
Thank you for your quick replies.
I am still facing some issues: the Preview in Info Tab stays empty, even though it is activated:
![image](https://user-images.githubusercontent.com/36054098/195903262-0d810ef0-47c2-4aaa-9ff2-c03f8e555597.png)
Restarting does not solve the problem.
The Preview in Preview Tab is working fine for the same PDF file:
![image](https://user-images.githubusercontent.com/36054098/195904005-69083527-79f1-4523-a099-1450dc2604b7.png)

I get the following error when clicking on a new item seeing the Preview in Info Tab:
`[JavaScript Error: "TypeError: iframe is null" {file: "chrome://pdfpreview/content/scripts/index.js" line: 402}]`

**Comment by volatile-static** [comment]
@mjthoraval  see #30

**Comment by windingwind** [comment]
fixed.

**Comment by mjthoraval** [comment]
Thank you very much for the fix.
I confirm that it is working fine now.
